[package]
name = "image_to_makecode"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.28", features = ["derive"] }
image = "0.25.5"
palette = "0.7.6"
pest = "2.7.15"
pest_derive = "2.7.15"
